import { describe, expect, test } from "vitest";
import {
  buildColumnDefinition,
  buildSequenceDefinition,
  quoteQualifiedSqlName,
  quoteSqlIdentifier,
  quoteSqlLiteral,
  sortViewsByDependency
} from "../src/main/postgres-dump";

describe("quoting helpers", () => {
  test("quotes identifiers and escapes embedded quotes", () => {
    expect(quoteSqlIdentifier("users")).toBe('"users"');
    expect(quoteSqlIdentifier('we"ird')).toBe('"we""ird"');
    expect(quoteQualifiedSqlName("public", "users")).toBe('"public"."users"');
  });

  test("quotes literals and escapes embedded quotes", () => {
    expect(quoteSqlLiteral("plain")).toBe("'plain'");
    expect(quoteSqlLiteral("it's")).toBe("'it''s'");
  });
});

describe("buildColumnDefinition", () => {
  test("renders plain columns with defaults and not null", () => {
    expect(
      buildColumnDefinition({
        name: "name",
        dataType: "text",
        notNull: true,
        defaultExpression: "'anon'::text",
        identity: "",
        generated: ""
      })
    ).toBe(`"name" text DEFAULT 'anon'::text NOT NULL`);
  });

  test("renders identity columns", () => {
    expect(
      buildColumnDefinition({
        name: "id",
        dataType: "bigint",
        notNull: true,
        defaultExpression: null,
        identity: "a",
        generated: ""
      })
    ).toBe(`"id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL`);
    expect(
      buildColumnDefinition({
        name: "id",
        dataType: "integer",
        notNull: false,
        defaultExpression: null,
        identity: "d",
        generated: ""
      })
    ).toBe(`"id" integer GENERATED BY DEFAULT AS IDENTITY`);
  });

  test("renders generated stored columns", () => {
    expect(
      buildColumnDefinition({
        name: "total",
        dataType: "numeric",
        notNull: false,
        defaultExpression: "(price * quantity)",
        identity: "",
        generated: "s"
      })
    ).toBe(`"total" numeric GENERATED ALWAYS AS ((price * quantity)) STORED`);
  });
});

describe("buildSequenceDefinition", () => {
  const base = {
    schema: "public",
    name: "users_id_seq",
    dataType: "bigint",
    startValue: "1",
    increment: "1",
    minValue: "1",
    maxValue: "9223372036854775807",
    cache: "1",
    cycle: false
  };

  test("renders default bigint sequences without AS clause", () => {
    expect(buildSequenceDefinition(base)).toBe(
      `CREATE SEQUENCE "public"."users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;`
    );
  });

  test("renders type, parameters, and cycle", () => {
    expect(
      buildSequenceDefinition({
        ...base,
        dataType: "integer",
        startValue: "100",
        increment: "5",
        maxValue: "2147483647",
        cycle: true
      })
    ).toBe(
      `CREATE SEQUENCE "public"."users_id_seq" AS integer INCREMENT BY 5 MINVALUE 1 MAXVALUE 2147483647 START WITH 100 CACHE 1 CYCLE;`
    );
  });
});

describe("sortViewsByDependency", () => {
  const view = (oid: string) => ({ oid, name: `view_${oid}` });

  test("orders a dependency chain source-first", () => {
    const views = [view("3"), view("1"), view("2")];
    // 3 depends on 2, 2 depends on 1
    const sorted = sortViewsByDependency(views, [
      { viewOid: "3", dependsOnOid: "2" },
      { viewOid: "2", dependsOnOid: "1" }
    ]);
    expect(sorted.map((item) => item.oid)).toEqual(["1", "2", "3"]);
  });

  test("orders a diamond before its dependents", () => {
    const views = [view("4"), view("2"), view("3"), view("1")];
    const sorted = sortViewsByDependency(views, [
      { viewOid: "4", dependsOnOid: "2" },
      { viewOid: "4", dependsOnOid: "3" },
      { viewOid: "2", dependsOnOid: "1" },
      { viewOid: "3", dependsOnOid: "1" }
    ]);
    const position = (oid: string) => sorted.findIndex((item) => item.oid === oid);
    expect(position("1")).toBeLessThan(position("2"));
    expect(position("1")).toBeLessThan(position("3"));
    expect(position("2")).toBeLessThan(position("4"));
    expect(position("3")).toBeLessThan(position("4"));
  });

  test("falls back to input order on cycles", () => {
    const views = [view("1"), view("2")];
    const sorted = sortViewsByDependency(views, [
      { viewOid: "1", dependsOnOid: "2" },
      { viewOid: "2", dependsOnOid: "1" }
    ]);
    expect(sorted.map((item) => item.oid)).toEqual(["1", "2"]);
  });

  test("ignores edges to unknown views", () => {
    const views = [view("2"), view("1")];
    const sorted = sortViewsByDependency(views, [
      { viewOid: "2", dependsOnOid: "1" },
      { viewOid: "2", dependsOnOid: "99" }
    ]);
    expect(sorted.map((item) => item.oid)).toEqual(["1", "2"]);
  });
});
